.env.example, .github/workflows/laravel.yml, app/Models/Company/EmployeePlannedHoliday.php, app/Services/Company/Employee/Holiday/CreateTimeOff.php, database/factories/CompanyFactory.php, database/migrations/2019_09_26_010323_create_employee_pto_table.php, database/migrations/2019_09_28_015610_create_company_calendar_table.php, docs/introduction.md, tests/Unit/Jobs/CalculateTimeOffBalanceTest.php, tests/Unit/Services/Company/Employee/Holiday/CreateTimeOffTest.php, tests/Unit/Services/Company/Employee/Holiday/ProcessDailyTimeOffBalanceTest.php
=> ci: setup github actions

app/Helpers/LogHelper.php, app/Models/Company/Team.php, app/Models/Company/TeamUsefulLink.php, app/Services/Company/Adminland/Company/GenerateDummyData.php, app/Services/Company/Team/Links/CreateTeamUsefulLink.php, database/factories/CompanyFactory.php, database/migrations/2019_12_03_030757_create_team_useful_links_table.php, docs/introduction.md, resources/lang/en/account.php, tests/Unit/Models/Company/TeamTest.php, tests/Unit/Models/Company/TeamUsefulLinkTest.php, tests/Unit/Services/Company/Team/Links/CreateTeamUsefulLinkTest.php
=> feat: service to create a team useful link

app/Helpers/LogHelper.php, app/Services/Company/Team/Links/DestroyTeamUsefulLink.php, resources/lang/en/account.php, tests/Unit/Services/Company/Team/Links/DestroyTeamUsefulLinkTest.php
=> feat: service to delete a team useful link

app/Models/Company/TeamUsefulLink.php, tests/Unit/Models/Company/TeamUsefulLinkTest.php
=> chore: return the right attribute for the team useful link label

.github/workflows/mysql.yml, .github/workflows/sqlite.yml
=> test: enhance github actions

.github/workflows/mysql.yml, .github/workflows/sqlite.yml, .github/workflows/static.yml, app/Http/Controllers/Company/Employee/EmployeeEditController.php, app/Http/Controllers/Company/Employee/EmployeeLogsController.php, app/Http/Controllers/Company/Employee/EmployeeWorklogController.php, app/Http/Controllers/Controller.php, tests/Unit/Controllers/ControllerTest.php
=> chore: change how permissions are made on the controllers

.env.ci.sqlite, .github/workflows/sqlite.yml, .github/workflows/static.yml, app/Exceptions/Handler.php, composer.json, composer.lock
=> chore: laravel 7

.sonarcloud.properties
=> ci: add sonarcloud

README.md, resources/js/Pages/Adminland/CompanyPTOPolicy/Index.vue, resources/js/Pages/Employee/Partials/PersonalDescription.vue
=> ci: add sonarcloud badges

.github/workflows/mysql.yml, phpunit.ci.mysql.xml
=> ci: add code coverage

.github/workflows/mysql.yml, app/Console/Kernel.php, app/Helpers/MapHelper.php, app/Helpers/WorklogHelper.php, app/Http/Controllers/Auth/RegisterController.php, app/Http/Controllers/Auth/UserInvitationController.php, app/Http/Controllers/Company/Adminland/AdminCompanyNewsController.php, app/Models/Company/Place.php, phpunit.ci.mysql.xml, sonarcloud.properties, tests/Unit/Helpers/MapHelperTest.php
=> chore: fix some sonarcloud bugs

README.md, app/Models/Company/EmployeeDailyCalendarEntry.php, database/factories/CompanyFactory.php, database/migrations/2019_09_26_010323_create_employee_pto_table.php
=> chore: remove useless info in daily calendar entries table

README.md, resources/js/Pages/Adminland/Employee/Index.vue, resources/js/Pages/Adminland/EmployeeStatus/Index.vue, resources/js/Pages/Adminland/Flow/ActionNotification.vue, resources/js/Pages/Adminland/Position/Index.vue, resources/js/Pages/Adminland/Team/Index.vue, resources/js/Pages/Dashboard/MyCompany.vue, resources/js/Pages/Dashboard/Team/Partials/Birthdays.vue, resources/js/Pages/Dashboard/Team/Partials/WorkFromHome.vue, resources/js/Pages/Employee/Index.vue, resources/js/Pages/Employee/Logs/Index.vue, resources/js/Pages/Employee/Partials/EmployeeGenderPronoun.vue, resources/js/Pages/Employee/Show.vue, resources/js/Pages/Team/Partials/Members.vue
=> chore: add lazy loading to images

README.md
=> chore: a bit more information on the readme

composer.lock, resources/js/Pages/Dashboard/Me/Partials/WorkFromHome.vue, resources/js/Shared/Checkbox.vue, resources/js/Shared/UserMenu.vue
=> chore: minor UI changes

app/Http/Controllers/Company/Employee/EmployeeController.php, app/Http/ViewHelpers/Company/Employee/EmployeeShowViewHelper.php, resources/js/Pages/Adminland/Hardware/Index.vue, resources/js/Pages/Employee/Partials/Hardware.vue, resources/js/Pages/Employee/Show.vue, resources/lang/en/employee.php, tests/Features/integration/employee/employee_hardware_spec.js, tests/Unit/ViewHelpers/Company/Employee/EmployeeShowViewHelperTest.php, yarn.lock
=> feat: view hardware on employee profile page

app/Helpers/LogHelper.php, app/Http/Controllers/Company/Adminland/AdminEmployeeController.php, composer.lock, config/officelife.php, resources/js/Pages/Adminland/Employee/Delete.vue, resources/js/Pages/Adminland/Employee/Index.vue, resources/lang/en/account.php, resources/lang/en/app.php, routes/web.php, tests/Features/integration/adminland/manage_employee_spec.js
=> feat: ability to delete an employee

app/Jobs/Dummy/AddDummyEmployeeToCompany.php, app/Jobs/Dummy/CreateDummyPosition.php, app/Jobs/Dummy/CreateDummyQuestion.php, app/Jobs/Dummy/CreateDummyTeam.php, app/Jobs/Dummy/CreateDummyWorklog.php, app/Models/Company/Employee.php, app/Models/Company/Worklog.php, app/Services/BaseService.php, app/Services/Company/Adminland/Company/GenerateDummyData.php, app/Services/Company/Adminland/Company/ProvisionDefaultAccountData.php, app/Services/Company/Adminland/Company/RemoveDummyData.php, app/Services/Company/Adminland/Employee/AddEmployeeToCompany.php, app/Services/Company/Adminland/Position/CreatePosition.php, app/Services/Company/Adminland/Team/CreateTeam.php, app/Services/Company/Employee/Birthdate/SetBirthdate.php, app/Services/Company/Employee/Worklog/LogWorklog.php, composer.lock, phpunit.xml, resources/lang/en/app.php, tests/Unit/Jobs/Dummy/AddDummyEmployeeToCompanyTest.php, tests/Unit/Jobs/Dummy/CreateDummyPositionTest.php, tests/Unit/Jobs/Dummy/CreateDummyTeamTest.php, tests/Unit/Services/BaseServiceTest.php, tests/Unit/Services/Company/Adminland/Company/GenerateDummyDataTest.php, tests/Unit/Services/Company/Adminland/Company/ProvisionDefaultAccountDataTest.php, tests/Unit/Services/Company/Employee/Worklog/LogWorklogTest.php
=> feat: generate dummy data now async

app/Http/Controllers/Company/Adminland/AdminEmployeeController.php, resources/js/Pages/Adminland/Employee/Create.vue, resources/js/Pages/Adminland/Employee/Index.vue, resources/js/Shared/Toaster.vue
=> feat: add indication of invitation on employee page

resources/js/Shared/Layout.vue
=> chore: improve search design

app/Helpers/LogHelper.php, app/Helpers/NotificationHelper.php, app/Http/Controllers/Company/Dashboard/DashboardMeController.php, app/Http/ViewHelpers/Dashboard/DashboardMeViewHelper.php, app/Models/Company/Company.php, app/Models/Company/Employee.php, app/Models/Company/Task.php, app/Models/Company/Team.php, app/Services/Company/Task/CreateTask.php, database/factories/CompanyFactory.php, database/migrations/2019_04_27_151029_create_tasks_table.php, resources/js/Pages/Dashboard/Me/Index.vue, resources/js/Pages/Dashboard/Me/Partials/Task.vue, resources/js/Pages/Dashboard/Me/Partials/Worklogs.vue, resources/lang/en/account.php, resources/lang/en/dashboard.php, tests/Unit/Models/Company/CompanyTest.php, tests/Unit/Models/Company/EmployeeTest.php, tests/Unit/Models/Company/TaskTest.php, tests/Unit/Models/Company/TeamTest.php, tests/Unit/Services/Company/Task/CreateTaskTest.php, tests/Unit/ViewHelpers/Dashboard/DashboardMeViewHelperTest.php
=> feat: display tasks on employee dashboard Verified

app/Helpers/LogHelper.php, app/Helpers/NotificationHelper.php, app/Http/Controllers/Company/Adminland/AdminExpenseController.php, app/Http/Controllers/Company/Adminland/PermissionController.php, app/Http/Controllers/Company/Dashboard/DashboardMeController.php, app/Http/Controllers/Company/Dashboard/DashboardTeamController.php, app/Http/ViewHelpers/Adminland/AdminExpenseViewHelper.php, app/Models/Company/Employee.php, app/Services/Company/Adminland/Employee/LockEmployee.php, app/Services/Company/Adminland/Expense/AllowEmployeeToManageExpenses.php, app/Services/Company/Adminland/Expense/DisallowEmployeeToManageExpenses.php, app/Services/Company/Employee/Notification/AddNotificationInUIForEmployee.php, composer.lock, database/migrations/2019_01_18_194542_create_employees_table.php, resources/js/Pages/Adminland/Expense/Index.vue, resources/js/Pages/Adminland/Expense/Partials/Categories.vue, resources/js/Pages/Adminland/Expense/Partials/Employees.vue, resources/js/Pages/Dashboard/MyCompany.vue, resources/js/Pages/Dashboard/Partials/DashboardMenu.vue, resources/js/Shared/Notifications.vue, resources/lang/en/account.php, resources/lang/en/dashboard.php, routes/web.php, tests/Features/integration/adminland/manage_expense_spec.js, tests/Features/integration/team/manage_team_recent_ships_spec.js, tests/Features/support/helpers/app.js, tests/Unit/Services/Company/Adminland/Employee/LockEmployeeTest.php, tests/Unit/Services/Company/Adminland/Expense/AllowEmployeeToManageExpensesTest.php, tests/Unit/Services/Company/Adminland/Expense/DisallowEmployeeToManageExpensesTest.php, tests/Unit/ViewHelpers/Adminland/AdminExpenseViewHelperTest.php
=> feat: add concept of accountants

app/Helpers/LogHelper.php, app/Helpers/NotificationHelper.php, app/Http/Controllers/Company/Dashboard/DashboardManagerController.php, app/Models/Company/Expense.php, app/Services/Company/Employee/Expense/AcceptExpenseAsAccountant.php, app/Services/Company/Employee/Expense/RejectExpenseAsAccountant.php, composer.lock, config/officelife.php, database/migrations/2020_06_30_211833_create_expenses_table.php, resources/js/Pages/Adminland/Expense/Index.vue, resources/js/Pages/Adminland/Expense/Partials/Categories.vue, resources/js/Pages/Adminland/Expense/Partials/Employees.vue, resources/js/Pages/Dashboard/Manager/Partials/Expense.vue, resources/lang/en/account.php, tests/Unit/Services/Company/Employee/Expense/AcceptExpenseAsAccountantTest.php, tests/Unit/Services/Company/Employee/Expense/RejectExpenseAsAccoutantTest.php
=> feat: services to accept or reject an expense as accountant

app/Helpers/LogHelper.php, app/Services/Company/Employee/Expense/AcceptExpenseAsAccountant.php, app/Services/Company/Employee/Expense/AcceptExpenseAsManager.php, app/Services/Company/Employee/Expense/RejectExpenseAsAccountant.php, app/Services/Company/Employee/Expense/RejectExpenseAsManager.php, resources/js/Pages/Employee/Logs/Index.vue, resources/lang/en/account.php, tests/Unit/Services/Company/Employee/Expense/AcceptExpenseAsAccountantTest.php, tests/Unit/Services/Company/Employee/Expense/AcceptExpenseAsManagerTest.php, tests/Unit/Services/Company/Employee/Expense/RejectExpenseAsAccoutantTest.php, tests/Unit/Services/Company/Employee/Expense/RejectExpenseAsManagerTest.php
=> feat: slight changes to the employee logs

app/Http/Controllers/Company/Adminland/AdminExpenseController.php, app/Http/ViewHelpers/Adminland/AdminExpenseViewHelper.php, resources/js/Pages/Adminland/Expense/Partials/Categories.vue, resources/js/Pages/Adminland/Expense/Partials/Employees.vue, resources/js/Pages/Dashboard/Expenses/Index.vue, resources/lang/en/account.php, routes/web.php, tests/Unit/ViewHelpers/Adminland/AdminExpenseViewHelperTest.php
=> feat: ability to rename and delete an expense category

app/Http/Controllers/Company/Team/TeamLeadController.php, app/Http/ViewHelpers/Team/TeamShowViewHelper.php, resources/js/Pages/Team/Show.vue, tests/Unit/ViewHelpers/Team/TeamShowViewHelperTest.php
=> fix: fix team page showing locked members 

resources/js/Pages/Team/Partials/Members.vue
=> fix: fix team members layout

app/Http/Controllers/Company/Adminland/AdminExpenseController.php, package.json, resources/js/Pages/Adminland/Expense/Partials/Categories.vue, tests/Features/integration/adminland/manage_expense_spec.js, yarn.lock
=> test: add tests for managing expense categories

app/Console/Commands/SetupDummyAccount.php, app/Helpers/LogHelper.php, app/Http/Controllers/Auth/LoginController.php, app/Http/Controllers/Company/Employee/EmployeeEditController.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, app/Models/Company/Employee.php, app/Services/BaseService.php, app/Services/Company/Employee/HiringDate/SetHiringDate.php, database/migrations/2019_01_18_194542_create_employees_table.php, database/migrations/2020_08_12_120202_create_rate_your_manager_table.php, resources/js/Pages/Employee/Edit.vue, resources/js/Pages/Employee/Partials/EmployeeHiredDate.vue, resources/js/Pages/Employee/Partials/HeaderEmployee.vue, resources/lang/en/account.php, resources/lang/en/employee.php, tests/Features/integration/employee/employee_hiring_date_information_spec.js, tests/Unit/Services/Company/Employee/HiringDate/SetHiringDateTest.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
=> feat: add hiring date information

resources/js/Shared/UserMenu.vue, resources/lang/en/app.php
=> chore: better user pop menu

app/Http/ViewHelpers/Dashboard/DashboardTeamViewHelper.php
=> chore: remove locked employees from dashboard team page

app/Console/Commands/SetupDummyAccount.php, app/Http/Controllers/Company/Dashboard/DashboardTeamController.php, app/Http/ViewHelpers/Dashboard/DashboardTeamViewHelper.php, config/officelife.php, resources/js/Pages/Dashboard/Team/Index.vue, resources/js/Pages/Dashboard/Team/Partials/UpcomingNewHires.vue, resources/js/Shared/UserMenu.vue, resources/lang/en/dashboard.php, tests/Features/integration/dashboard/dashboard_team_spec.js, tests/Features/integration/employee/employee_log_expense_spec.js, tests/Unit/ViewHelpers/Dashboard/DashboardTeamViewHelperTest.php
=> feat: show upcoming hires on team dashboard

app/Http/Controllers/Company/Dashboard/DashboardMeOneOnOneController.php, app/Http/Controllers/Company/Employee/EmployeeController.php, app/Http/Controllers/Company/Employee/EmployeeOneOnOneController.php, app/Http/Controllers/Company/Employee/EmployeePerformanceController.php, app/Http/ViewHelpers/Dashboard/DashboardMeViewHelper.php, app/Http/ViewHelpers/Employee/EmployeeOneOnOneViewHelper.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, composer.lock, config/officelife.php, resources/js/Pages/Dashboard/Me/Partials/Expense.vue, resources/js/Pages/Dashboard/Me/Partials/OneOnOneWithManager.vue, resources/js/Pages/Dashboard/Me/Partials/RateYourManager.vue, resources/js/Pages/Dashboard/Me/Partials/Worklogs.vue, resources/js/Pages/Employee/Expenses/Index.vue, resources/js/Pages/Employee/OneOnOnes/Index.vue, resources/js/Pages/Employee/OneOnOnes/Show.vue, resources/js/Pages/Employee/Partials/Expenses.vue, resources/js/Pages/Employee/Partials/Hardware.vue, resources/js/Pages/Employee/Partials/OneOnOneWithManager.vue, resources/js/Pages/Employee/Partials/Question.vue, resources/js/Pages/Employee/Partials/Worklogs.vue, resources/js/Pages/Employee/Performance/Index.vue, resources/js/Pages/Employee/Show.vue, resources/lang/en/app.php, resources/lang/en/employee.php, routes/web.php, tests/Features/integration/dashboard/dashboard_one_on_ones_spec.js, tests/Unit/ViewHelpers/Employee/EmployeeExpenseViewHelperTest.php, tests/Unit/ViewHelpers/Employee/EmployeeOneOnOneViewHelperTest.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
=> feat: add one on one on employee profile page

app/Console/Commands/SetupDummyAccount.php, app/Services/Company/Employee/OneOnOne/MarkOneOnOneEntryAsHappened.php
=> chore: fix seeding script not working for one on one entries

.github/workflows/build.yml, .github/workflows/static.yml
=> chore: fix branch name

.github/workflows/build.yml, sonar-project.properties, sonarcloud.properties
=> chore: run sonarcloud from github action

sonar-project.properties
=> chore: exclude migration files from duplicate alerts in sonarcloud

.github/workflows/build.yml, phpunit.xml, sonar-project.properties, tests/Integration/SetupDummyAccountTest.php, tests/Integration/SetupFrontEndTestTest.php
=> chore: split tests in multiple testsuites and activate code coverage

README.md, sonar-project.properties
=> chore: fix sonar coverage

.github/workflows/build.yml, sonar-project.properties, tests/.env.ci-sqlite
| | without coverage | with coverage |
|---|---|---|
| Unit test | 30s | 3min |
| Integration test | 1min |
| | without coverage | with coverage |
|---|---|---|
| Unit test | 55s | 1min45s |
| Integration test | 2min35s |
We could run
unit test on mysql with code coverage (=1min45sec)
unit test and integration test with sqlite (without code coverage) (=2min10sec total)
integration test will not run with mysql (anyway, they are just test for command which will never run on production)
=> chore: change coverage settings

composer.lock, yarn.lock
=> chore(deps): update composer and yarn

app/Http/Controllers/Company/Company/CompanyController.php, app/Http/ViewHelpers/Company/CompanyQuestionViewHelper.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, resources/js/Pages/Company/Index.vue, resources/js/Pages/Company/Partials/Questions.vue, resources/js/Pages/Company/Partials/RecentSkills.vue, resources/js/Shared/Layout.vue, resources/lang/en/company.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: improvement on the company page

app/Helpers/LogHelper.php
Replace all the `ifs` by a `switch case` statement.
=> refactor: greatly improve loghelper performance

composer.lock, yarn.lock
=> chore: update composer and yarn

resources/js/Pages/Adminland/Employee/Index.vue, resources/js/Pages/Employee/Edit.vue, resources/js/Pages/Employee/Edit/Address.vue, resources/js/Pages/Employee/Expenses/Index.vue, resources/js/Pages/Employee/Partials/Skills.vue, resources/js/Shared/Checkbox.vue, resources/js/Shared/EditableCheckbox.vue, resources/js/Shared/Errors.vue, resources/js/Shared/FileInput.vue, resources/js/Shared/Layout.vue, resources/js/Shared/Select.vue, resources/js/Shared/TextArea.vue, resources/js/Shared/TextInput.vue
=> fix: fix some vue object types

app/Exceptions/Handler.php, app/Http/Controllers/Auth/LoginController.php, resources/js/Pages/Auth/Login.vue, routes/web.php
This allow to
- keep user logged in when they return to the app after a while
- use built-in Laravel method to do the authentication
=> feat: improve login and allow to remember credentials

app/Services/Company/Adminland/Company/CreateCompany.php, app/Services/Company/Adminland/Employee/AddEmployeeToCompany.php, app/Services/User/Avatar/GenerateAvatar.php, tests/Unit/Services/User/Avatar/GenerateAvatarTest.php
Adorable avatars are gone. We need to replace it with another one... for now, until we get the ability to upload files.
cc @asbiin
=> feat: replace adorable avatar by another api

docs/installation/heroku.md
=> docs: fix heroku doc

app/Services/Company/Adminland/Company/CreateCompany.php
When you've just register, it's not possible to create a new company because of this.
=> fix: fix company create for the first user

.github/workflows/build.yml
=> ci: fix git complain message in tests

app/Http/Controllers/Company/Project/ProjectController.php, resources/js/Pages/Project/Members/Index.vue, resources/js/Pages/Project/Partials/ProjectUpdates.vue
=> chore: fix permissions on summary project page

resources/js/Pages/Auth/Login.vue, resources/js/Pages/Auth/Register.vue, resources/js/Pages/Home/CreateCompany.vue, resources/js/app.js
=> chore: add the $route prototype

app/Helpers/LogHelper.php, app/Helpers/NotificationHelper.php, app/Helpers/RandomHelper.php, resources/js/Pages/Adminland/Expense/Index.vue, resources/js/Pages/Adminland/Expense/Partials/Employees.vue, resources/js/Pages/Company/Partials/RecentSkills.vue, resources/js/Pages/Dashboard/Manager/Partials/OneOnOneWithDirectReport.vue, resources/js/Pages/Dashboard/Me/Partials/Expense.vue, resources/js/Pages/Dashboard/Me/Partials/RateYourManager.vue, resources/js/Pages/Dashboard/Me/Partials/Task.vue, resources/js/Pages/Employee/Expenses/Index.vue, resources/js/Pages/Employee/OneOnOnes/Index.vue, resources/js/Pages/Employee/Partials/EmployeeGenderPronoun.vue, resources/js/Pages/Employee/Partials/EmployeePosition.vue, resources/js/Pages/Employee/Partials/EmployeeStatus.vue, resources/js/Pages/Employee/Partials/EmployeeTeam.vue, resources/js/Pages/Employee/Partials/OneOnOneWithManager.vue, resources/js/Pages/Employee/Partials/Skills.vue, resources/js/Pages/Employee/Performance/Surveys/Index.vue, resources/js/Pages/Employee/Performance/Surveys/Show.vue, resources/js/Pages/Employee/WorkFromHome/Index.vue, resources/js/Pages/Employee/Worklogs/Index.vue, resources/js/Pages/Team/Ship/Create.vue, resources/js/Shared/Checkbox.vue, resources/js/Shared/EditableCheckbox.vue, resources/js/Shared/Toaster.vue, routes/api.php, routes/web.php, tests/Unit/Helpers/LogHelperTest.php, tests/Unit/Helpers/NotificationHelperTest.php
=> refactor: fix some sonarcloud issues

.github/workflows/automerge.yml, .github/workflows/build.yml, .github/workflows/static.yml
This will also trigger the needed workflows when "Compress images" workflow is triggered.
=> ci: add automerge workflow

.github/workflows/build.yml, .github/workflows/static.yml
=> ci: filter branch on workflow run

phpstan.neon
=> fix: fix phpstan conf

.github/workflows/automerge.yml, .github/workflows/build.yml, .github/workflows/static.yml
=> ci: fix workflow run again

.github/workflows/automerge.yml, .github/workflows/build.yml, .github/workflows/static.yml
=> ci: deactivate automerge

resources/js/Pages/Employee/Partials/EmployeeGenderPronoun.vue, resources/js/Pages/Employee/Partials/EmployeePosition.vue, resources/js/Pages/Team/Partials/TeamUsefulLink.vue, tests/Features/integration/company/company_skills_spec.js, tests/Features/integration/company_spec.js, tests/Features/integration/employee/assign_employee_statuses_spec.js, tests/Features/integration/employee/assign_gender_pronouns_to_employee_spec.js, tests/Features/integration/employee/assign_positions_spec.js, tests/Features/integration/employee/employee_edit_address_spec.js, tests/Features/integration/employee/employee_log_expense_spec.js, tests/Features/integration/employee/employee_rate_your_manager_spec.js, tests/Features/integration/help_spec.js, tests/Features/integration/project/manage_project_links_spec.js, tests/Features/support/helpers/app.js
=> test: fix lots of cypress tests

app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, resources/js/Pages/Company/Partials/RecentSkills.vue, resources/lang/en/account.php, tests/Features/integration/adminland/manage_questions_spec.js, tests/Features/integration/company/company_skills_spec.js, tests/Features/integration/employee/employee_edit_personal_information_spec.js, tests/Features/integration/employee/employee_work_from_home_spec.js, tests/Features/integration/employee/managers_and_direct_reports_spec.js, tests/Features/integration/project/manage_project_links_spec.js, tests/Features/integration/team/manage_team_recent_ships_spec.js
=> test: fix cypress bugs

sonar-project.properties
=> ci: exclude controllers from coverage

.github/workflows/docker.yml, scripts/package.sh
=> ci: build docker image for main branch

app/Http/Middleware/CheckCompany.php, composer.json, composer.lock, psalm.xml
=> chore(deps): update deps

.github/workflows/docker.yml
=> ci: use docker github action

resources/js/Pages/Adminland/CompanyNews/Index.vue, resources/js/Pages/Adminland/EmployeeStatus/Index.vue, resources/js/Pages/Adminland/Expense/Partials/Categories.vue, resources/js/Pages/Adminland/Position/Index.vue, resources/js/Pages/Adminland/Question/Index.vue, resources/js/Pages/Adminland/Team/Index.vue, resources/js/Pages/Auth/Invitation/AcceptInvitation.vue, resources/js/Pages/Auth/Invitation/AcceptInvitationUnlogged.vue, resources/js/Pages/Auth/Login.vue, resources/js/Pages/Auth/Register.vue, resources/js/Pages/Auth/VerifyEmail.vue, resources/js/Pages/Dashboard/Me/Partials/Expense.vue, resources/js/Pages/Employee/Partials/Hierarchy.vue, resources/js/Pages/Employee/Partials/Skills.vue, resources/js/Pages/Home/CreateCompany.vue, resources/js/Shared/UserMenu.vue, resources/js/app.js
This fix #395, after upgrade of ziggy in #393 
=> fix: fix vue.js route after ziggy update

composer.lock
=> chore(deps): upgrade deps

.github/workflows/cypress.yml
=> chore: change cypress context name

app/Services/Company/Employee/Expense/CreateExpense.php, tests/Unit/Services/Company/Employee/Expense/CreateExpenseTest.php
=> fix: fix expense to be stricly positive

app/Console/Commands/Tests/SetupDummyAccount.php, app/Helpers/LogHelper.php, app/Http/Controllers/Company/Employee/EmployeeEditController.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, app/Models/Company/Employee.php, app/Services/Company/Employee/Contract/SetContractRenewalDate.php, database/migrations/2020_12_16_143950_add_contract_renewal_date_to_employees.php, resources/js/Pages/Employee/Edit.vue, resources/js/Pages/Employee/Edit/Address.vue, resources/js/Pages/Employee/Edit/Contract.vue, resources/js/Pages/Employee/Partials/EmployeeRenewalDate.vue, resources/js/Pages/Employee/Partials/HeaderEmployee.vue, resources/lang/en/account.php, resources/lang/en/employee.php, routes/web.php, tests/Unit/Services/Company/Employee/Contract/SetContractRenewalDateTest.php, tests/Unit/ViewHelpers/Adminland/AdminGeneralViewHelperTest.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
This PR adds a contract renewal date for external contractors.
=> feat: add ability to set a contract renewal date

app/Helpers/LogHelper.php, app/Http/Controllers/Company/Dashboard/DashboardManagerController.php, app/Http/ViewHelpers/Dashboard/DashboardManagerViewHelper.php, resources/js/Pages/Dashboard/Manager/Index.vue, resources/js/Pages/Dashboard/Manager/Partials/ContractRenewal.vue, resources/js/Pages/Employee/OneOnOnes/Show.vue, resources/lang/en/dashboard.php, tests/Unit/ViewHelpers/Dashboard/DashboardManagerViewHelperTest.php
=> feat: employees with contract renewal date on manager dashboard

.github/dependabot.yml, dependabot.yml
=> chore: add dependabot file

.github/dependabot.yml
=> chore: add dependabot labels

app/Http/Controllers/Company/Dashboard/DashboardTimesheetController.php
=> fix: fix days in timesheet header not showing

package.json
=> ci: run yarn prod for heroku in a dedicated script

app/Services/Company/Employee/Timesheet/ApproveTimesheet.php, app/Services/Company/Employee/Timesheet/RejectTimesheet.php, tests/Unit/Services/Company/Employee/Timesheet/ApproveTimesheetTest.php, tests/Unit/Services/Company/Employee/Timesheet/RejectTimesheetTest.php
I forgot to add these two information on the services 🤦
=> feat: add approver id and name for a timesheet

.github/workflows/lock.yml
=> ci: add lock-thread action workflow

.releaserc, scripts/package.sh
=> fix: fix release script

.github/workflows/build.yml
=> ci: fix release with changelog file

app/Http/Controllers/Company/Dashboard/DashboardTimesheetController.php, app/Services/Company/Employee/Timesheet/DestroyTimesheetRow.php, resources/js/Pages/Dashboard/Timesheet/Index.vue, resources/js/Pages/Dashboard/Timesheet/Partials/TimesheetRow.vue, routes/web.php, tests/Unit/Services/Company/Employee/Timesheet/DestroyTimesheetRowTest.php
=> feat: ability to delete a timesheet row

app/Console/Commands/Tests/SetupDummyAccount.php, app/Http/Controllers/Company/Dashboard/DashboardTimesheetController.php, app/Http/ViewHelpers/Dashboard/DashboardTimesheetViewHelper.php, resources/js/Pages/Dashboard/Timesheet/Index.vue, resources/js/Pages/Dashboard/Timesheet/Partials/TimesheetRow.vue, resources/lang/en/dashboard.php, tests/Unit/ViewHelpers/Dashboard/DashboardTimesheetViewHelperTest.php
=> feat: notify employee when a timesheet is rejected

LICENSE, README.md, app/Http/ViewHelpers/Dashboard/DashboardTeamViewHelper.php
Change badges and some details.
Back to 120k lines of code, happy @djaiss ?
=> style: change badges and some details on readme

app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, resources/js/Pages/Employee/Edit/Contract.vue, resources/js/Pages/Employee/Partials/EmployeeStatus.vue, resources/lang/en/employee.php, routes/web.php, tests/Features/integration/employee/employee_consultant_information_spec.js, tests/Features/support/helpers/app.js, tests/Unit/Services/Company/Employee/ConsultantRate/DestroyConsultantRateTest.php, tests/Unit/Services/Company/Employee/ConsultantRate/SetConsultantRateTest.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
=> feat: display contract info on employee profile page

.devcontainer/Dockerfile
=> chore: install sqlite3 for codespace

.releaserc, CHANGELOG.md, scripts/commit-changelog.sh
=> ci: update changelog when semantic-release

.github/workflows/build.yml
=> ci: add missing plugin to semantic release

package.json, yarn.lock
=> chore(deps): update inertia

app/Http/ViewHelpers/Adminland/AdminGeneralViewHelper.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, resources/js/Pages/Company/Partials/NewHires.vue, resources/lang/en/company.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> refactor: fix tests that fail sometimes in the ci for obscure reasons

scripts/commit-changelog.sh
=> chore(changelog): remove uppercase

.github/workflows/build.yml, scripts/commit-changelog.sh
=> ci: fix package creation

.devcontainer/devcontainer.json, .github/workflows/cypress.yml, scripts/package.sh
=> build: add missing yarn prod

phpunit.xml
=> test: change phpunit config

.github/workflows/release.yml, .releaserc
=> build: remove non-used config

app/Http/ViewHelpers/Company/Project/ProjectTasksViewHelper.php
=> test: fix it_gets_a_collection_of_tasks_with_task_lists(): void

app/Http/ViewHelpers/Team/TeamShowViewHelper.php
=> test: fix it_gets_a_collection_of_recent_ships

.github/workflows/build-assets.yml, .github/workflows/build.yml, .github/workflows/cypress.yml, .github/workflows/docker.yml, .github/workflows/release.yml, .github/workflows/static.yml, composer.lock
=> ci: use full php 8.0 env

.github/workflows/build.yml, routes/web.php
=> fix: fix artisan route:cache

resources/js/Pages/Company/Partials/GuessEmployeeGame.vue, resources/js/Shared/Layout.vue
=> feat: allow to escape find by clic

resources/js/Shared/Layout.vue
=> feat: cache results of search

.github/workflows/build-assets.yml, config/cache.php, fortrabbit.yml
=> feat: add fortrabbit configuration

phpunit.xml
=> test: fix variable for tests

.github/workflows/deploy.yml
=> ci: activate deployment

.github/workflows/deploy.yml, config/sentry.php
=> ci: create sentry release when deploying

composer.json, composer.lock, config/insights.php
Try with
```console
php artisan insights
```
Next we should integrate it in Github action with https://github.com/stefanzweifel/laravel-phpinsights-action
=> ci: add phpinsights

resources/js/Pages/Dashboard/Timesheet/Index.vue
=> fix: hide rejected timesheets when there are none

app/Http/Controllers/Company/Employee/EmployeeEditController.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, resources/js/Pages/Employee/Edit.vue, resources/js/Pages/Employee/Edit/Address.vue, resources/js/Pages/Employee/Edit/Contract.vue
=> fix: fix permission to edit contract information

app/Http/ViewHelpers/Adminland/AdminGeneralViewHelper.php, resources/js/Pages/Adminland/General/Index.vue, resources/js/Pages/Adminland/General/Partials/Name.vue, resources/js/Pages/Adminland/General/Partials/Stat.vue
=> feat: better layout for the company settings page

app/Http/Controllers/Company/Company/CompanyController.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, app/Models/User/Pronoun.php, resources/js/Pages/Company/Index.vue, resources/js/Pages/Company/Partials/Employees.vue, resources/js/Pages/Company/Partials/NewHires.vue, resources/js/Pages/Employee/Administration/Index.vue, resources/js/Pages/Employee/Index.vue, resources/js/Pages/Employee/Performance/Index.vue, resources/js/Pages/Employee/Show.vue, resources/js/Pages/Employee/Work/Index.vue, resources/lang/en/company.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: new employee widget on company tab

app/Http/Controllers/Company/Company/CompanyController.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, resources/js/Pages/Company/Index.vue, resources/js/Pages/Company/Partials/Employees.vue, resources/js/Pages/Company/Partials/Teams.vue, resources/js/Pages/Team/Index.vue, resources/js/Pages/Team/Show.vue, resources/lang/en/company.php, routes/web.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: new team widget on company tab

app/Http/Controllers/Company/Company/CompanyNewsController.php, app/Http/Controllers/Company/Dashboard/DashboardController.php, app/Http/ViewHelpers/Company/CompanyNewsViewHelper.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, app/Http/ViewHelpers/Dashboard/DashboardOneOnOneViewHelper.php, resources/js/Pages/Adminland/CompanyNews/Index.vue, resources/js/Pages/Company/Index.vue, resources/js/Pages/Company/News/Index.vue, resources/js/Pages/Company/Partials/Birthdays.vue, resources/js/Pages/Company/Partials/CompanyNews.vue, resources/js/Pages/Company/Partials/Employees.vue, resources/js/Pages/Company/Partials/Questions.vue, resources/js/Pages/Company/Partials/RecentShips.vue, resources/js/Pages/Company/Partials/RecentSkills.vue, resources/js/Pages/Company/Partials/Teams.vue, resources/js/Pages/Company/Project/Index.vue, resources/lang/en/app.php, resources/lang/en/company.php, routes/web.php, tests/Unit/ViewHelpers/Company/CompanyNewsViewHelperTest.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: better company news on the company tab

resources/js/Pages/Dashboard/Me/Partials/ECoffee.vue
=> fix: fix avatar on dashboard

app/Http/Controllers/Company/Dashboard/DashboardMeController.php, app/Http/ViewHelpers/Company/Project/ProjectViewHelper.php, app/Http/ViewHelpers/Dashboard/DashboardMeViewHelper.php, resources/js/Pages/Company/Project/Create.vue, resources/js/Pages/Company/Project/Partials/ProjectMenu.vue, resources/js/Pages/Dashboard/Me/Index.vue, resources/js/Pages/Dashboard/Me/Partials/Projects.vue, resources/lang/en/dashboard.php, tests/Unit/ViewHelpers/Company/Project/ProjectViewHelperTest.php, tests/Unit/ViewHelpers/Dashboard/DashboardMeViewHelperTest.php
=> feat: display projects of employees on summary page

.releaserc
=> ci: allow semantic-release to work on main branch

config/trustedproxy.php
=> refactor: apply trustedproxy config

app/Http/Controllers/Company/Team/TeamController.php, app/Http/ViewHelpers/Dashboard/DashboardTeamViewHelper.php, app/Http/ViewHelpers/Team/TeamIndexViewHelper.php, app/Http/ViewHelpers/Team/TeamShowViewHelper.php, resources/js/Pages/Team/Index.vue, resources/js/Pages/Team/Partials/Birthdays.vue, resources/js/Pages/Team/Show.vue, resources/lang/en/team.php, tests/Unit/ViewHelpers/Team/TeamIndexViewHelperTest.php, tests/Unit/ViewHelpers/Team/TeamShowViewHelperTest.php
=> feat: display upcoming birthdates on team page

yarn.lock
=> chore(deps): upgrade npm dependencies

app/Http/Controllers/Company/Dashboard/DashboardTimesheetController.php
=> fix: fix header not showing on dashboard timesheet page

config/cache.php
=> fix: fix memcache config

config/cache.php
=> refactor: remove memcache specific config

.github/workflows/deploy.yml
=> ci: change deploy command

README.md
=> docs: add more information to readme

README.md
=> docs: what is officelife

app/Http/Controllers/Company/Adminland/AdminEmployeeController.php, app/Services/Company/Adminland/Employee/AddEmployeeToCompany.php, resources/js/Pages/Adminland/Employee/Create.vue, resources/lang/en/account.php, resources/lang/en/app.php, tests/Unit/Services/Company/Adminland/Employee/AddEmployeeToCompanyTest.php
=> fix: fix employees can be added with an email adress already used

resources/js/Pages/Adminland/CompanyPTOPolicy/Index.vue
=> fix: fix calendar not showing in company pto policy page

webpack.mix.js
=> fix: fix assets production build

app/Helpers/LogHelper.php, app/Http/Controllers/Company/Adminland/AdminGeneralController.php, app/Http/ViewHelpers/Adminland/AdminGeneralViewHelper.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, app/Models/Company/Company.php, app/Services/Company/Adminland/Company/UpdateCompanyFoundedDate.php, database/migrations/2021_04_13_002821_add_company_creation_date_to_company_table.php, resources/js/Pages/Adminland/General/Index.vue, resources/js/Pages/Adminland/General/Partials/FoundedDate.vue, resources/js/Pages/Adminland/General/Partials/Name.vue, resources/js/Pages/Company/Index.vue, resources/lang/en/account.php, resources/lang/en/company.php, routes/web.php, tests/Unit/Services/Company/Adminland/Company/UpdateCompanyFoundedDateTest.php, tests/Unit/ViewHelpers/Adminland/AdminGeneralViewHelperTest.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: ability to set company founded date

resources/js/Pages/Dashboard/Me/Partials/Morale.vue
=> fix: fix morale help link

config/officelife.php, resources/js/Pages/Adminland/General/Partials/FoundedDate.vue
=> docs: add link to documentation for founded date

app/Http/ViewHelpers/Company/CompanyQuestionViewHelper.php, resources/js/Pages/Adminland/Question/Index.vue, resources/js/Pages/Company/Question/Index.vue, tests/Unit/ViewHelpers/Company/CompanyQuestionViewHelperTest.php
This PR change the behavior of displaying questions.
If a question is active but has no answer, you can now see it in the questions list.
Also fix the display when there is no question, and a glitch in the message translation.
=> refactor: change question display

app/Helpers/DateHelper.php, tests/Unit/Helpers/DateHelperTest.php
=> refactor: update the format day and month date helper to take timezone into account

resources/js/Pages/Company/Project/Partials/ProjectLinks.vue
=> fix: fix project add links

app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, resources/js/Pages/Adminland/Employee/Create.vue, resources/js/Pages/Employee/Partials/EmployeeImportantDates.vue, resources/lang/en/employee.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
=> feat: display number of employees hired after employee

app/Http/Controllers/Company/Company/CompanyController.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, app/Http/ViewHelpers/Company/HR/CompanyHRViewHelper.php, app/Http/ViewHelpers/Dashboard/DashboardTeamViewHelper.php, resources/js/Pages/Company/Index.vue, resources/js/Pages/Company/Partials/UpcomingHiringDateAnniversaries.vue, resources/lang/en/company.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: display upcoming work anniversaries on company page

app/Http/Controllers/Company/Team/TeamController.php, app/Http/ViewHelpers/Team/TeamShowViewHelper.php, resources/js/Pages/Team/Partials/Morale.vue, resources/js/Pages/Team/Partials/NewHiresNextWeek.vue, resources/js/Pages/Team/Show.vue, resources/lang/en/dashboard.php, resources/lang/en/team.php, tests/Unit/ViewHelpers/Team/TeamShowViewHelperTest.php
=> feat: display upcoming new hires in team page

.github/workflows/deploy.yml
=> ci: fix sentry release

composer.json, composer.lock
=> chore(dev-deps): update dependencies

database/migrations/2021_04_20_180102_create_sessions_table.php
=> refactor: add session table

composer.json, composer.lock
=> refactor: add intl extension

app/Jobs/ProcessCompanyMorale.php
=> fix: fix company morale job not being processed for companies without employees

.github/workflows/deploy.yml, .github/workflows/release.yml
=> ci: fix sentry sourcemaps upload

.github/workflows/deploy.yml
=> ci: fix sentry sourcemaps upload again

resources/js/sentry.js
=> fix: fix sentry setContext

app/Services/Company/Project/CloseProject.php, tests/Unit/Services/Company/Project/CloseProjectTest.php
=> feat: add date when project was marked as completed

resources/js/Pages/Company/Project/Partials/ProjectUpdates.vue, resources/js/Pages/Company/Project/Tasks/Show.vue, resources/js/Shared/TextDuration.vue, resources/lang/en/project.php
=> fix: fix project time tracking not working

.github/workflows/build.yml, .github/workflows/cypress.yml, .github/workflows/deploy.yml, .github/workflows/release.yml, config/officelife.php, config/sentry.php, scripts/package.sh
=> build: change package build

.devcontainer/devcontainer.json, .github/workflows/cypress.yml, .github/workflows/deploy.yml, .github/workflows/release.yml, .releaserc, package.json, scripts/package.sh
=> build: fix release package build

README.md, app/Console/Commands/Tests/SetupDummyAccount.php, app/Helpers/DateHelper.php, app/Http/Controllers/Company/Employee/Presentation/EmployeePresentationController.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, app/Models/Company/Employee.php, app/Models/Company/EmployeePositionHistory.php, app/Models/Company/Position.php, app/Services/Company/Employee/Position/AssignPositionToEmployee.php, database/factories/Company/EmployeePositionHistoryFactory.php, database/migrations/2021_04_25_171141_add_position_history_table.php, resources/js/Pages/Employee/Partials/EmployeePastPositions.vue, resources/js/Pages/Employee/Partials/EmployeeStatus.vue, resources/js/Pages/Employee/Show.vue, resources/lang/en/employee.php, resources/lang/en/format.php, tests/Unit/Helpers/DateHelperTest.php, tests/Unit/Models/Company/EmployeePositionHistoryTest.php, tests/Unit/Models/Company/EmployeeTest.php, tests/Unit/Models/Company/PositionTest.php, tests/Unit/Services/Company/Employee/Position/AssignPositionToEmployeeTest.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
=> feat: record employee position history in the company

app/Http/ViewHelpers/Dashboard/DashboardViewHelper.php, database/factories/Company/EmployeeFactory.php, resources/js/Pages/Dashboard/Partials/DashboardMenu.vue, tests/Unit/ViewHelpers/Dashboard/DashboardViewHelperTest.php
=> feat: make the avatar of the employee clickable on dashboard

.github/workflows/calibreapp-image-actions.yml
=> ci: update calibreapp action

.github/workflows/calibreapp-image-actions.yml
=> ci: fix calibreapp again

app/Http/ViewHelpers/Company/CompanyViewHelper.php, resources/js/Pages/Company/Group/Index.vue, resources/js/Pages/Company/HR/Index.vue, resources/js/Pages/Company/Index.vue, resources/js/Pages/Company/Partials/Header.vue, resources/js/Pages/Company/Project/Index.vue, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
=> feat: better header on company page

resources/js/Pages/Adminland/Employee/Partials/EmployeeList.vue
=> feat: better indicator of employee being invited

resources/js/Pages/Company/Partials/Header.vue
=> feat: remove the url of the company on company page

.github/workflows/release.yml
=> build: fix package release files

app/Http/Controllers/Auth/RegisterController.php, resources/js/Pages/Adminland/Index.vue, resources/js/Pages/Auth/Register.vue, resources/lang/en/auth.php
We'll add it back later once we manage holidays and PTOs for real.
=> chore: remove the option to manage pto for now

app/Helpers/DateHelper.php, phpunit.xml, resources/lang/en/format.php, tests/Unit/Helpers/DateHelperTest.php, tests/Unit/Models/Company/CompanyNewsTest.php, tests/Unit/Models/Company/EmployeeLogTest.php, tests/Unit/Models/Company/TeamLogTest.php, tests/Unit/Models/Company/TeamNewsTest.php, tests/Unit/ViewHelpers/Adminland/AdminAuditLogViewHelperTest.php, tests/Unit/ViewHelpers/Adminland/AdminGeneralViewHelperTest.php, tests/Unit/ViewHelpers/Adminland/AdminTeamViewHelperTest.php, tests/Unit/ViewHelpers/Adminland/AdminUploadEmployeeViewHelperTest.php, tests/Unit/ViewHelpers/Employee/EmployeeLogViewHelperTest.php
=> refactor: fix date format consistency

resources/js/Pages/Employee/Partials/Avatar.vue, resources/js/Shared/Avatar.vue
=> feat: banner on profile image showing we can change avatar

app/Helpers/LocaleHelper.php, composer.json, composer.lock, config/app.php, config/lang-detector.php
=> feat: detect language from browser

app/Http/Controllers/User/LocaleController.php, app/Http/Middleware/ShareInertiaData.php, app/Models/User/User.php, app/Services/User/UpdateLocale.php, resources/js/Pages/Profile/Partials/UpdateLocale.vue, resources/js/Pages/Profile/Show.vue, resources/js/app.js, resources/js/langs.js, resources/lang/fr/app.php, tests/Unit/Services/User/UpdateLocaleTest.php
=> feat: change language dynamically

app/Models/Company/Employee.php, resources/js/Shared/Layout.vue
=> feat: add a footer explaining the beta version

app/Console/Commands/Tests/SetupDummyAccount.php, resources/js/Pages/Auth/Login.vue
=> refactor: update password for demo account

resources/js/Pages/Dashboard/Partials/DashboardMenu.vue, resources/lang/en/dashboard.php
=> chore(i18n): fix localize welcome message

.github/workflows/deploy.yml, config/cache.php, config/sentry.php
=> build: deploy on demo

app/Models/User/User.php
=> feat: use locale of user in notifications

.github/workflows/deploy.yml, scripts/.htaccess_production
Use https://help.fortrabbit.com/htaccess feature
=> feat: redirect trafic to https

app/Console/Kernel.php
This raised an issue on Sentry https://sentry.io/organizations/officelife/issues/2437906181/?project=5674916
=> chore: disable cron for ptos

app/Http/Controllers/HomeController.php, resources/js/Shared/UserMenu.vue, routes/web.php
=> feat: skip home if employee has 1 company

app/Console/Commands/Demo/ResetDemo.php, app/Console/Kernel.php
=> style: limit demo:reset command

app/Console/Commands/Demo/ResetDemo.php, app/Console/Kernel.php
=> fix: fix demo reset

resources/js/Pages/Auth/Partials/Languages.vue
=> style: change language style

resources/js/Pages/Auth/Login.vue, resources/js/Shared/TextInput.vue
=> style: fix errors style display

app/Console/Kernel.php, app/Http/Controllers/Company/Adminland/AdminExpenseController.php, app/Services/Company/GuessEmployeeGame/VoteGuessEmployeeGame.php, resources/js/Pages/Company/Partials/GuessEmployeeGame.vue, resources/js/Pages/Profile/Partials/UpdateLocale.vue
This fix #976 by removing the trailing slash '/' at the end of the axios url @djaiss 
Also change demo reset schedule, and other fixes...
=> fix: fix guess employee vote and other things

app/Helpers/LogHelper.php
=> fix: fix admin log view agenda_item_created

app/Jobs/ConvertExpense.php, app/Services/Company/Adminland/Expense/ConvertAmountFromOneCurrencyToCompanyCurrency.php, app/Services/Company/Place/GetGPSCoordinate.php, tests/Unit/Services/Company/Adminland/Expense/ConvertAmountFromOneCurrencyToCompanyCurrencyTest.php, tests/Unit/Services/Company/Place/GetGPSCoordinateTest.php
=> refactor: remove Guzzle usages

resources/js/Pages/Adminland/Employee/Import.vue, resources/lang/en/employee.php, resources/lang/fr/employee.php, resources/lang/nb_NO/employee.php, resources/lang/ru/employee.php
=> fix: fix edit employee twitter help message

app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php
=> fix: remove timezones from dates on employee profile

resources/js/Pages/Dashboard/Timesheet/Index.vue
=> fix: fix broken link to create project on timesheet view

resources/js/Pages/Dashboard/Me/Partials/ECoffee.vue
=> fix: fix text overriden avatars on ecoffee widgets

app/Console/Commands/Demo/ResetDemo.php
=> fix: fix reset demo download issues

app/Http/Controllers/Company/Company/Project/ProjectController.php
=> fix: fix search without pattern

app/Http/ViewHelpers/Employee/EmployeeEditViewHelper.php, resources/js/Pages/Employee/Edit/Contract.vue, tests/Unit/ViewHelpers/Employee/EmployeeEditViewHelperTest.php
=> fix: fix contract rate store

app/Http/ViewHelpers/Employee/EmployeeEditViewHelper.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, resources/js/Pages/Employee/Edit/Contract.vue, tests/Unit/ViewHelpers/Employee/EmployeeEditViewHelperTest.php
Sentry issue: https://sentry.io/organizations/officelife/issues/2448116368/?environment=production&project=5674916&referrer=alert_email
=> fix: fix edit contract page being shown for non external employees

resources/js/Pages/Adminland/Employee/Archives/Index.vue
=> chore: change color of importing state during employees import

resources/lang/en/account.php, tests/Unit/Services/Company/Adminland/Software/CreateSoftwareTest.php, tests/Unit/Services/Company/Adminland/Software/DestroySoftwareTest.php, tests/Unit/Services/Company/Adminland/Software/GiveSeatToEmployeeTest.php, tests/Unit/Services/Company/Adminland/Software/GiveSeatToEveryEmployeeTest.php, tests/Unit/Services/Company/Adminland/Software/TakeSeatFromEmployeeTest.php, tests/Unit/Services/Company/Adminland/Software/UpdateSoftwareTest.php
=> chore: fix plural label

resources/js/Pages/Adminland/Software/Show.vue, resources/lang/en/account.php
=> chore: fix plural again

app/Services/Company/Adminland/Employee/LockEmployee.php
When we locked an employee, we kept the hierarchy between the locked employee and the managers/direct reports.
This lead to errors for pending expenses, which were in a blocked status as no one could approve/reject them.
This PR changes that.
=> feat: remove employee hierarchy when locking employees

sonar-project.properties
=> build: remove coverage on factories

app/Helpers/BirthdayHelper.php, app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php, app/Models/Company/Employee.php, tests/Unit/Helpers/BirthdayHelperTest.php, tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
=> fix: fix age calculation using timezone

app/Exceptions/ConvertAmountException.php, app/Services/Company/Adminland/Expense/ConvertAmountFromOneCurrencyToCompanyCurrency.php, app/Services/Company/Employee/Expense/CreateExpense.php, config/logging.php, tests/Fixtures/Services/Adminland/Expense/currencylayer_fail.json, tests/Unit/Services/Company/Adminland/Expense/ConvertAmountFromOneCurrencyToCompanyCurrencyTest.php
=> feat: add sentry logger channel

app/Helpers/LogHelper.php
Fix https://sentry.io/organizations/officelife/issues/2440259593/?project=5674916&query=is%3Aunresolved
=> fix: fix audit log for updated agenda item action

database/migrations/2021_06_15_165524_add_uui_to_failed_job.php
This fixes the first problem listed here https://github.com/officelifehq/officelife/issues/1076.
=> fix: add missing field in the failed jobs table

app/Http/Controllers/Company/Adminland/AdminSoftwareController.php
=> fix: remove pagination in software page 

app/Http/ViewHelpers/Company/HeaderSearchViewHelper.php, app/Http/ViewHelpers/Employee/EmployeeSkillViewHelper.php, resources/js/Shared/Layout.vue, tests/Unit/ViewHelpers/Company/HeaderSearchViewHelperTest.php, tests/Unit/ViewHelpers/Employee/EmployeeSkillViewHelperTest.php
=> fix: fix search with empty criteria

app/Services/Company/Employee/OneOnOne/CreateOneOnOneNote.php, resources/js/Pages/Dashboard/OneOnOnes/Partials/Note.vue
=> fix: fix one on one note length

app/Http/ViewHelpers/Adminland/AdminSoftwareViewHelper.php, resources/js/Pages/Adminland/Software/Edit.vue
=> fix: fix order number in software that can not be edited

app/Console/Kernel.php
@asbiin until we understand why the company is deleted.
=> chore: disable auto reset of demo instance

app/Http/Controllers/Company/Company/Project/ProjectTasksController.php, app/Http/ViewHelpers/Company/Project/ProjectTasksViewHelper.php, app/Services/Company/Project/UpdateProjectTask.php, resources/js/Pages/Company/Project/Tasks/Index.vue, resources/js/Pages/Company/Project/Tasks/Partials/ProjectTasks.vue, resources/js/Pages/Company/Project/Tasks/Show.vue, resources/lang/en/project.php, tests/Unit/ViewHelpers/Company/Project/ProjectTasksViewHelperTest.php
This solves https://github.com/officelifehq/officelife/discussions/1066
=> feat: change task list when editing a task in a project

.editorconfig, app.json, app/Providers/RouteServiceProvider.php
=> feat: force https when using production env

app.json
=> fix: fix heroku configuration file

app/Http/Controllers/Company/Company/HR/CompanyHRController.php, app/Http/Controllers/Company/Company/HR/CompanyHRPositionController.php, app/Http/ViewHelpers/Company/HR/CompanyHRPositionShowViewHelper.php, app/Http/ViewHelpers/Company/HR/CompanyHRViewHelper.php, resources/js/Pages/Company/HR/Index.vue, resources/js/Pages/Company/HR/Partials/Genders.vue, resources/js/Pages/Company/HR/Partials/Positions.vue, resources/js/Pages/Company/HR/Positions/Show.vue, resources/lang/en/app.php, resources/lang/en/company.php, routes/web.php, tests/Unit/ViewHelpers/Company/HR/CompanyHRPositionShowViewHelperTest.php, tests/Unit/ViewHelpers/Company/HR/CompanyHRViewHelperTest.php
=> feat: display stats about positions in the company

composer.json, composer.lock
We don't use this package. See #1266
=> chore(deps): remove paratest

composer.json, composer.lock
@asbiin using clockwork wasn't a good idea. It's less user friendly than Debugbar.
=> chore: use debugbar instead of clockwork

resources/js/Pages/Company/Project/Tasks/Partials/ProjectTaskCheckbox.vue, resources/js/Pages/Company/Project/Tasks/Partials/ProjectTasks.vue
=> fix: fix tasks overflow when text is too big

resources/js/Pages/Dashboard/Me/Partials/Expense.vue
=> feat: increase expense maximum amount

app/Http/ViewHelpers/Company/CompanyNewsViewHelper.php, app/Http/ViewHelpers/Company/CompanyViewHelper.php, resources/js/Pages/Company/News/Index.vue, resources/js/Pages/Company/Partials/CompanyNews.vue, tests/Unit/ViewHelpers/Company/CompanyNewsViewHelperTest.php, tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
- better markdown support
- date on company news index list
=> feat: markdown support for company news

resources/js/Shared/Layout.vue
Recruiting is not ready yet to be played with.
=> chore: hide recruiting tab for now

app/Http/Controllers/Company/Recruiting/RecruitingJobOpeningController.php, app/Http/ViewHelpers/Dashboard/DashboardMeViewHelper.php, package.json, resources/js/Shared/Select.vue, resources/lang/en/app.php, yarn.lock
Vue-select was broken in our setup.
I'm sick of having broken dependencies, so I kinda rewrite it - even though it's not as great as what vue-select offered.
=> fix: fix vue-select not working by rewriting it

composer.lock
=> chore(deps): update packages

resources/js/Pages/Welcome/Index.vue
Simple change to open admin guide in new tab when opening it from the welcome screen.
=> feat: open admin guide from welcome screen in new tab

composer.lock
=> chore(deps): composer update

app/Helpers/InstanceHelper.php, app/Models/Company/Employee.php, tests/Unit/Models/Company/EmployeeTest.php
Somehow, in production right now, caching is not working. To bypass this, we won't use the cache to retrieve the logged employee, just to make sure this is not what's causing the problem in production.
=> fix: fix instance helper for now

app/Http/Controllers/Company/Adminland/AdminRecruitmentController.php, app/Http/ViewHelpers/Adminland/AdminRecruitmentViewHelper.php, composer.lock, resources/js/Pages/Adminland/Recruitment/Index.vue, routes/web.php, tests/Unit/ViewHelpers/Adminland/AdminRecruitmentViewHelperTest.php
=> fix: fix mixed content error on recruitment process
