officelifehq/officelife

- app/Services/Company/Employee/OneOnOne/CreateOneOnOneEntry.php
Marking an entry as `happened` creates a new one on one entry, with unchecked action items of current entry being transferred as talking points in the new entry.
However, the CreateOneOnOneEntry service fetched the previous entry based on the creation date, and not the date the one on one happened. This was a bug.
> fix: fix one on one entries not being sorted by happened date

- .github/workflows/build.yml
> ci: stop running sonarcloud for dependabot branches

- .gitignore
We need to keep `.DS_store` in gitignore (which @asbiin you removed last week) because it’s added everywhere on macOS and will be a constant pain for all devs that might contribute to the project. It’s better to put it back.
> chore: put back DS_store in gitignore

- webpack.mix.js
- Add ball-pulse css class name to purgecss' whitelist
- Also add 'false' parameter to sourcemap to not create them on production
> fix: fix ball-pulse css removal

- Procfile
- app.json
- app/Console/Commands/Helpers/Command.php
- app/Console/Commands/Helpers/CommandCaller.php
- app/Console/Commands/Helpers/CommandCallerContract.php
- app/Console/Commands/Setup.php
- app/Providers/AppServiceProvider.php
- tests/Helpers/CommandCallerFake.php
- tests/Unit/Commands/SetupCommandTest.php
This adds a new command called 'setup' to run all needed operations to install or update the application.
- config clear/cache
- cache clear
- view clear/cache
- route clear/cache
- migration
> ci: add a setup command

- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Kernel.php
- app/Http/Middleware/EnsureEmailIsVerified.php
- app/Models/User/User.php
- config/mail.php
This adds a new `MAIL_VERIFY` environment variable to disable email verification (true by default = enabled).
Cypress tests will require MAIL_VERIFY=false
> feat: add an option to disable mail verification

- resources/js/Pages/Dashboard/Me/Index.vue
This PR hides the "one on one with manager" widget on the employee dashboard when he has no manager.
> chore: hide one on one when no manager on dashboard

- app/Http/Controllers/Company/Employee/EmployeeController.php
- app/Http/Controllers/Company/Employee/EmployeePerformanceController.php
- app/Http/Controllers/Company/Employee/EmployeeStatusController.php
- app/Http/Middleware/CheckCompany.php
- app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php
- resources/js/Pages/Employee/Partials/EmployeeStatus.vue
- resources/js/Pages/Employee/Partials/HeaderEmployee.vue
- resources/js/Pages/Employee/Performance/Index.vue
- resources/js/Pages/Employee/Show.vue
- routes/web.php
- tests/Unit/ViewHelpers/Employee/EmployeeShowViewHelperTest.php
The employee statuses, on the employee profile page, have some problems.
1. The query to fetch them is done all the time, even if the employee can’t change statuses.
2. They use a previous concept of "collections" that I implemented two years ago, but it’s a really bad idea as a concept, for a lot of reasons.
In #436, I’m changing how employee statuses work under the hood, and I need the improvements I've done in this PR for this.
I wanted to split the work in smaller PR so #436 is not too big.
In short, this PR
* loads employee statuses on demand on the Employee profile page
* is the first step to enable the removal of the EmployeeStatusCollection method.
Note: ideally, all the data in the header of an Employee profile page should be loaded asynchronously, but we have to do it slowly, …
> feat: load employee statuses on demand

- resources/js/Pages/Dashboard/Expenses/Index.vue
- resources/js/Pages/Dashboard/Manager/Index.vue
- resources/js/Pages/Dashboard/Me/Index.vue
- resources/js/Pages/Dashboard/Partials/DashboardMenu.vue
- resources/js/Pages/Dashboard/Team/Index.vue
- resources/js/Shared/Layout.vue
- resources/lang/en/app.php
In the coming weeks I'll simplify the navigation.
I've started here to remove elements that won't be that used in the header of the app, like Teams or Employees. Those two options will be found later on in the Company tab.
> refactor: simpler navigation

- app/Console/Commands/Tests/VerifyEmailOfLastCreatedEmployee.php
- tests/Features/support/helpers/app.js
- tests/Integration/VerifyEmailOfLastCreatedEmployeeTest.php
Putting in place the email verification broke many Cypress tests, because now when we switch accounts to checks specific flows in Cypress, we are stuck in the Please verify email accounts page.
This PR tries to fix that by creating a new command that indicates an account has been verified already.
It’s a bit of a hack, but it works.
cc @asbiin
> fix: fix email verification in cypress

- app/Helpers/BirthdayHelper.php
- app/Helpers/DateHelper.php
- app/Http/ViewHelpers/Company/CompanyViewHelper.php
- app/Http/ViewHelpers/Dashboard/DashboardHRViewHelper.php
- app/Http/ViewHelpers/Dashboard/DashboardManagerViewHelper.php
- app/Http/ViewHelpers/Dashboard/DashboardMeViewHelper.php
- app/Http/ViewHelpers/Dashboard/DashboardTeamViewHelper.php
- app/Http/ViewHelpers/Employee/EmployeeOneOnOneViewHelper.php
- app/Http/ViewHelpers/Employee/EmployeePerformanceViewHelper.php
- app/Http/ViewHelpers/Employee/EmployeeShowViewHelper.php
- app/Http/ViewHelpers/Employee/EmployeeSurveysViewHelper.php
- app/Models/Company/Employee.php
> fix: fix Carbon::now() calls in loops

- app/Http/ViewHelpers/Company/CompanyViewHelper.php
SQLSTATE[42000]: Syntax error or access violation: 1055 'officelife.questions.title' isn't in GROUP BY
> fix: fix company questions query

- tests/Unit/HelpCenterTest.php
Improve test speed: 6992ms -> 852ms
> test: use guzzle to test help links

- app/Services/User/CreateAccount.php
I have NO idea how it's possible, but somehow the verification email is sent twice during registration.
When I delete the line where we send the email ourself, the email is only sent twice.
So it fixes the bug. BUT...
As the line to send the email is deleted, why do we still send the email? I think it's because of Fortify somehow. I've read the entire Fortify codebase but I don't see anywhere how come it sends an email.
So. The bug is fixed but I don't know why the app keeps sending the email.
> fix: fix verification email being sent twice

- .env.example
- config/officelife.php
support@officelife.io should not be used as a default email administrator value for every person that will use the project.
The value of EMAIL_INSTANCE_ADMINISTRATOR must be set on each instance with a proper value, but we must not get emails from every instance!
> style: remove support default email admin

- app/Http/Middleware/ShareInertiaData.php
- app/Services/User/CreateAccount.php
- resources/js/Pages/Auth/Login.vue
- resources/js/Pages/Auth/Partials/Languages.vue
- resources/js/Pages/Auth/Register.vue
- resources/js/Shared/Layout/AuthenticationCard.vue
- resources/lang/en/auth.php
- On Register page, you can select a language, and this language will be used as user's locale.
- On Login page, you can select a language, but the user's locale will be used later.
> feat: choose language on register and login forms

- app/Http/Controllers/Company/Adminland/AdminEmployeeStatusController.php
- app/Http/ViewHelpers/Adminland/AdminEmployeeStatusViewHelper.php
- resources/js/Pages/Adminland/EmployeeStatus/Index.vue
- tests/Unit/ViewHelpers/Adminland/AdminEmployeeStatusViewHelperTest.php
Another refactor.
@djaiss see how AdminEmployeeStatusViewHelper::index is easy to read now.
> refactor: remove employee type_translated

- app/Jobs/ServiceQueue.php
- app/Services/Company/Adminland/Employee/ImportEmployeesFromCSV.php
- app/Services/Company/Adminland/Employee/ImportEmployeesFromTemporaryTable.php
- app/Services/Company/Group/AddEmployeeToGroup.php
- app/Services/DispatchableService.php
- app/Services/QueuableService.php
- tests/Unit/Jobs/ServiceQueueTest.php
- tests/Unit/Jobs/ServiceQueueTester.php
- tests/Unit/Services/Company/Adminland/Employee/ImportEmployeesFromCSVTest.php
- tests/Unit/Services/Company/Adminland/Employee/ImportEmployeesFromTemporaryTableTest.php
- tests/Unit/Services/Company/Group/AddEmployeeToGroupTest.php
This makes the QueuableService implementation even easier
You can call a service with
```
Service::dispatch($data);
```
or
```
(new Service($data))->handle();
```
If you need to get a result, the service can also implement another function like:
```
$result = (new Service)->execute($data);
```
or even
```
$result = (new Service($data))->execute();
```
It also simplify the workflow of calling validate twice ... if a service run on the queue, the validation only happens on the queue run (like before with specific jobs)
So we don't need the `init(array $data)` function anymore, and the trick with `validate()` that return an array (that was a bad idea).
Implementing this to transform an existing service is then really easy:
1. add `implements QueuableService`
2. add `use Dispatchable`
3.a. if …
> refactor: simplify queuable service

- resources/js/Pages/Dashboard/Me/Partials/Expense.vue
> fix: fix illustration on expense hiding help text

- app/Helpers/MoneyHelper.php
- app/Http/Controllers/Company/Dashboard/Me/DashboardMeExpenseController.php
- tests/Unit/Helpers/MoneyHelperTest.php
All money don't use 2 minorUnit (2 cents numbers).
`MoneyHelper::parseInput` helps to parse the input
> fix: ability to use money with different minorUnit

- app/Exceptions/MalformedCSVException.php
- app/Services/Company/Adminland/Employee/ImportEmployeesFromCSV.php
- resources/js/Pages/Adminland/Employee/Archives/Show.vue
- resources/lang/en/account.php
- tests/Fixtures/Services/Adminland/Employee/Imports/working.csv
- tests/Unit/Services/Company/Adminland/Employee/ImportEmployeesFromCSVTest.php
> feat: check csv validity before processing it

- database/migrations/2014_10_12_200000_add_two_factor_columns_to_users_table.php
@asbiin we can't drop two columns in the same migration with sqlite (see https://laravel.com/docs/master/migrations#dropping-columns).
Moreover, there is no need to use `down` methods. We never use them.
> chore: remove migration that does not work with sqlite

- resources/js/Pages/Adminland/CompanyNews/Create.vue
- resources/js/Shared/TextInput.vue
This will be necessary for the Flow feature.
This adds a counter indicating how many characters remain in the input text field.
This appears when we indicate a new props: `maxlength`. When defined, it will show the counter.
> feat: add remaining characters left in input text fields

- app/Helpers/PermissionHelper.php
- resources/js/Pages/Employee/Edit.vue
- tests/Unit/Helpers/PermissionHelperTest.php
Being able to edit contract info doesn't mean you should be able to see the tab that lets you edit contract info.
> fix: fix permissions to edit employee contract info

- app/Http/Controllers/Company/Company/Project/ProjectController.php
- app/Http/Controllers/Company/Company/Project/ProjectDecisionsController.php
- app/Http/Controllers/Company/Company/Project/ProjectFilesController.php
- app/Http/Controllers/Company/Company/Project/ProjectMembersController.php
- app/Http/Controllers/Company/Company/Project/ProjectMessagesController.php
- app/Http/Controllers/Company/Company/Project/ProjectTaskListsController.php
- app/Http/Controllers/Company/Company/Project/ProjectTasksController.php
PhpDoc Fixed
We don't need to add `Illuminate\Routing\Redirector` in most PHP function docs because `redirect()` helper is never passed blank or null in these files.
> fix: Fix PhpDoc in project namespace

- app/Http/ViewHelpers/Adminland/AdminExpenseViewHelper.php
- app/Http/ViewHelpers/Adminland/AdminSoftwareViewHelper.php
- app/Http/ViewHelpers/Company/Group/GroupCreateViewHelper.php
- app/Http/ViewHelpers/Company/Group/GroupMeetingsViewHelper.php
- app/Http/ViewHelpers/Company/HR/CompanyHRViewHelper.php
- app/Http/ViewHelpers/Company/Project/ProjectDecisionsViewHelper.php
- app/Http/ViewHelpers/Company/Project/ProjectViewHelper.php
- app/Http/ViewHelpers/Dashboard/DashboardHRViewHelper.php
- app/Http/ViewHelpers/Dashboard/HR/DashboardHRTimesheetViewHelper.php
- app/Http/ViewHelpers/Employee/EmployeeHierarchyViewHelper.php
- app/Http/ViewHelpers/Employee/EmployeeSkillViewHelper.php
- app/Http/ViewHelpers/Team/TeamMembersViewHelper.php
- app/Http/ViewHelpers/Team/TeamRecentShipViewHelper.php
- app/Http/ViewHelpers/Team/TeamShowViewHelper.php
- app/Models/Company/Employee.php
- tests/Unit/ViewHelpers/Employee/EmployeeHierarchyViewHelperTest.php
> fix: fix search function to accept null criteria as empty query string

- resources/js/Pages/Adminland/Billing/Index.vue
- resources/lang/en/account.php
> fix: fix blank state message on billing screen

- .gitignore
- app/Services/Company/Adminland/Expense/ConvertAmountFromOneCurrencyToCompanyCurrency.php
- database/migrations/2020_06_30_211833_create_expenses_table.php
- database/migrations/2021_07_13_164157_fix_expense_converted_amount.php
- tests/Unit/Services/Company/Adminland/Expense/ConvertAmountFromOneCurrencyToCompanyCurrencyTest.php
Amount **must** **ALWAYS** be saved as integer.
In this case, `converted_amount` is also render later using `MoneyHelper::format()` which take the amount as an integer.
Notes:
- the migration in `2021_07_13_164157_fix_expense_converted_amount.php` use a `change()` which does not work on sqlite (it locks the table!)
- that's why I've updated the columns in `2020_06_30_211833_create_expenses_table.php` also: it will apply for sqlite, or new installation, which is fine, and the migration will not apply to existing installation, which is fine too (the 2nd migration will fix it)
---
> fix: fix convertamount format

- app/Http/ViewHelpers/Adminland/AdminGeneralViewHelper.php
- app/Models/Company/Company.php
- app/Services/Company/Adminland/Company/CreateCompany.php
- app/Services/Company/Adminland/Company/RenameCompany.php
- app/Services/Company/Adminland/Company/UpdateCompanySlug.php
- database/factories/Company/CompanyFactory.php
- database/migrations/2021_08_02_184706_add_company_slug_to_companies.php
- tests/Unit/Services/Company/Adminland/Company/CreateCompanyTest.php
- tests/Unit/Services/Company/Adminland/Company/RenameCompanyTest.php
- tests/Unit/Services/Company/Adminland/Company/UpdateCompanySlugTest.php
- tests/Unit/ViewHelpers/Adminland/AdminGeneralViewHelperTest.php
This PR adds a slug to a company object.
Basically, if a company is called `Basecamp`, the slug of the company will be `basecamp`.
If there is already a company with this slug, the slug will be `basecamp-2` instead.
This will be used in #1175, when we will display the open job openings for everyone on the Internet to see.
> feat: automatic slug when creating or renaming a company

- composer.json
- composer.lock
- storage/clockwork/.gitignore
Clockwork looks like a great alternative to debugbar.
Debugbar is still great, but it messes with the requests as code is injected into the HTML.
Clockwork, instead, logs everything into a JSON file and we need a browser extension to read the information.
Also, it allows us to debug information with the `clock()` helper, like `clock(User::first(), auth()->user(), $username)`.
> chore: use clockwork instead of debugbar

- app/Http/ViewHelpers/Company/CompanyViewHelper.php
- tests/Unit/ViewHelpers/Company/CompanyViewHelperTest.php
This is because sometimes, CI is so fast that the `latest()` eloquent method, which is based on the timestamps, does not give the intended results.
To be more precise, timestamps in Laravel are limited to seconds, and CI can go so fast that two objects are created in the same second, so the `latest` method does not return the items in the right order.
> ci: fix failing test

- app/Jobs/StopRateYourManagerProcess.php
Fix https://github.com/officelifehq/officelife/issues/1282
> fix: fix stop rate manager process not stopping surveys

- app/Http/ViewHelpers/Company/Group/GroupMeetingsViewHelper.php
- app/Http/ViewHelpers/Company/Group/GroupShowViewHelper.php
- resources/js/Pages/Company/Group/Meetings/Partials/Agenda.vue
- tests/Unit/ViewHelpers/Company/Group/GroupMeetingsViewHelperTest.php
- tests/Unit/ViewHelpers/Company/Group/GroupShowViewHelperTest.php
> fix: show only members who were present in the meeting
